var constant = {
  "WECHAT_SESSION": "NS:API:WECHAT_SESSION:",
  "CATERING_SESSION": "NS:API:CATERING_SESSION:",

  "AUDIT_INFO": "NS:API:AUDIT_INFO:",
  "USER_INFO": "NS:API:USER_INFO:",
  "STORE_INFO": "NS:API:STORE_INFO:",

  "EXPIRE_REFRESH": 86400,
}

module.exports = constant